colorscheme serenity-white
hook global RegisterModified '"' %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | wl-copy > /dev/null 2>&1 &
}}
map global user P '!wl-paste -n<ret>'
map global user p '<a-!>wl-paste -n<ret>'
map global user R '|wl-paste -n<ret>'
